[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
order_book_dex = "4z84hS8fsVpBgZvNwPtH82uUrjuoGP5GkRrTKkAaFDc9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
